version: '3.8'

services:
  blogapi:
    build:
      context: ./BlogApi
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DatabaseSettings__ConnectionString=mongodb://admin:admin123@mongo:27017
      - DatabaseSettings__DatabaseName=BlogPost
    ports:
      - "5010:8080"
    depends_on:
      - mongo
    networks:
      - blog_network

  mongo:
    image: mongo:latest
    container_name: blogapi-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - blog_network

volumes:
  mongo-data:
    driver: local

networks:
  blog_network:
    driver: bridge
